### ISSUE TITLE
Scorpio: some improvement required

### ISSUE THREAD

**Issue by yyk808** [open-rust-initiative/mega#682]
### In the past few days I tested scorpio for integrating zed with mega and here are my suggestions for it. 

- [x] **Gracefully start and quit:** When scorpio receives a signal to quit, it won't umount the mountpoint. Causing it cannot correctly start in the next time.

- [x] **Confusing meanings for _mount_:**   `mountpoint` and `mount` doesn't share the same meaning 
https://github.com/web3infra-foundation/mega/blob/c64b9e938f80d8ceffb249dd5ca05cc792b1f60d/scorpio/src/main.rs#L30
https://github.com/web3infra-foundation/mega/blob/c64b9e938f80d8ceffb249dd5ca05cc792b1f60d/scorpio/src/deamon/mod.rs#L84

- [x] **mountpoint should not be hard-coded**: request it from `/api/config` would be nice.
- [ ] **Duplicated _mount_ paths:** Simply call `/api/mount` on the same path twice and you'll got:
![{7B6BC589-F056-4707-92A2-B5EAE032039E}](https://github.com/user-attachments/assets/c1356714-f9f7-4289-b382-dcfa63ee2180)
- [ ] **Let's use absolute path:** Just a suggestion.
- [ ] **IO Error on reading non-exist files:** Using `cat` command for a non-exsiting file in the fuse would get a `IO Error` message.
![{3229F94F-EE80-469D-9610-EC5530707324}](https://github.com/user-attachments/assets/08820c71-0829-41b3-a1d9-fe6a730c1959)

**Comment by yyk808** [comment]
@Ivanbeethoven

**Comment by Ivanbeethoven** [comment]
Got it !

**Comment by Ivanbeethoven** [comment]
PRs #688 and #687  has solved the problems :
- [x] Gracefully start and quit
- [x] Confusing meanings for mount
- [x] mountpoint should not be hard-coded
- [x] Duplicated mount paths： Now you can't mount twice

## TODO:
- [ ] IO Error on reading non-exist files : need some error check with libc function .
- [ ] Let's use absolute path
